### ISSUE TITLE
HELP - Unable to find token seed! Did https://translate.google.com change?

### ISSUE THREAD

**Issue by Joregsor** [Boudewijn26/gTTS-token#20]
Im having the ValueError "Unable to find token seed! Did https://translate.google.com change?" in this code:

from gtts import gTTS
tts = gTTS('hello')
ValueError: Unable to find token seed! Did https://translate.google.com change?

is there any fixes? I have been having this error for several days and it does not allow me to advance in certain projects

Thank you.

**Comment by hmmbob** [comment]
Hello @Boudewijn26,

Your package is being used within Home Assistant and many users are running into the same problem as described above (see https://github.com/home-assistant/core/issues/42911).  Are you still maintaining this package? And if so, could you have a look?

Thanks!

**Comment by Boudewijn26** [comment]
Hi guys,

It's always been my honor to be some part of Home Assistant. I hope to be able to spend some time this evening (GMT+1) investigating what Google changed and how we might adapt. I'll try to tackle the open issues at the same time. I'll keep you updated.

**Comment by Boudewijn26** [comment]
This should be resolved with the release of 1.1.4. Special thanks to @w2sv for his retry mechanism.

Feel free to reopen if the issue persists or pop up again.
